In [56]:
import pandas as pd
pd.set_option('display.max_columns', 999)
pd.set_option('display.max_rows', 30)

df_sc_players = pd.read_csv('inputs/2020 SC player list.csv')
df_sc_players['player_team_id'] = df_sc_players['SC Player Name'].str.upper() + '_' + df_sc_players['Team'].str.upper()
df_sc_players

,SC ID,SC Feed ID,SC Player Name,first_name,last_name,Fanfooty Player ID,Fanfooty Player Name,Footywire Name,AFL ID,AFL Name,Team,Position,Date of Birth,Jumper Number,player_team_id
0,1,294472,Rory Atkins,Rory,Atkins,NaN,NaN,NaN,NaN,NaN,ADE,MID,NaN,NaN,RORY ATKINS_ADE
1,2,293193,Luke Brown,Luke,Brown,NaN,NaN,NaN,NaN,NaN,ADE,DEF,NaN,NaN,LUKE BROWN_ADE
2,3,1004995,Jordon Butts,Jordon,Butts,NaN,NaN,NaN,NaN,NaN,ADE,DEF,NaN,NaN,JORDON BUTTS_ADE
3,4,993796,Ben Crocker,Ben,Crocker,NaN,NaN,NaN,NaN,NaN,ADE,FWD,NaN,NaN,BEN CROCKER_ADE
4,5,294307,Brad Crouch,Brad,Crouch,NaN,NaN,NaN,NaN,NaN,ADE,MID,NaN,NaN,BRAD CROUCH_ADE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810,812,996554,Jake Waterman,Jake,Waterman,NaN,NaN,NaN,NaN,NaN,WCE,FWD,NaN,NaN,JAKE WATERMAN_WCE
811,813,298474,Francis Watson,Francis,Watson,NaN,NaN,NaN,NaN,NaN,WCE,DEF,NaN,NaN,FRANCIS WATSON_WCE
812,814,1006114,Bailey Williams,Bailey,Williams,NaN,NaN,NaN,NaN,NaN,WCE,DEF,NaN,NaN,BAILEY WILLIAMS_WCE
813,815,292128,Elliot Yeo,Elliot,Yeo,NaN,NaN,NaN,NaN,NaN,WCE,MID,NaN,NaN,ELLIOT YEO_WCE
814,816,291773,Jack Newnes,Jack,Newnes,NaN,NaN,NaN,NaN,NaN,CAR,MID,NaN,NaN,JACK NEWNES_CAR

In [57]:
df_team_names = pd.read_csv('inputs/all_sources_team_names.csv')
df_fanfooty_players = pd.read_csv('inputs/2020_fanfooty_player_list_with_ids.csv')

df_fanfooty_players.columns = ['fanfooty_player_id', 'afl_player_id', 'first_name', 'surname', 'team', 'status', 'number', 'birth_date', 'height', 'weight', 'state_of_origin', 'recruited_from', 'games', 'goals']
df_fanfooty_players['short_team'] = df_fanfooty_players['team'].map(dict(df_team_names[['footywire_team_name', 'sc_team_name']].values))
df_fanfooty_players['player_team_id'] = df_fanfooty_players['first_name'].str.upper() + ' ' + df_fanfooty_players['surname'].str.upper() + '_' + df_fanfooty_players['short_team'].str.upper()
df_fanfooty_players

,fanfooty_player_id,afl_player_id,first_name,surname,team,status,number,birth_date,height,weight,state_of_origin,recruited_from,games,goals,short_team,player_team_id
0,43031,294472,Rory,Atkins,Adelaide,senior,21,12/07/1994,186,85,VIC,Calder Cannons,97.0,"45""",ADE,RORY ATKINS_ADE
1,42301,293193,Luke,Brown,Adelaide,senior,16,22/09/1992,181,81,SA,Norwood,150.0,"13""",ADE,LUKE BROWN_ADE
2,49119,1004995,Jordon,Butts,Adelaide,rookie,41,31/12/1999,198,83,VIC,Murray Bushrangers,NaN,"""",ADE,JORDON BUTTS_ADE
3,46036,993796,Ben,Crocker,Adelaide,rookie,20,19/02/1997,188,84,VIC,Oakleigh Chargers,26.0,"21""",ADE,BEN CROCKER_ADE
4,42260,294307,Brad,Crouch,Adelaide,senior,2,14/01/1994,186,85,VIC,North Ballarat Rebels,83.0,"32""",ADE,BRAD CROUCH_ADE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
810,47013,998172,Tim,Taranto,GWS,senior,14,28/01/1998,187,87,VIC,Sandringham Dragons,59.0,"23""",GWS,TIM TARANTO_GWS
811,48201,1005247,Sam,Taylor,GWS,senior,15,5/05/1999,196,93,WA,Swan Districts,26.0,"1""",GWS,SAM TAYLOR_GWS
812,39670,280109,Callan,Ward,GWS,senior,8,10/04/1990,187,84,VIC,Western Jets,216.0,"107""",GWS,CALLAN WARD_GWS
813,43001,294305,Lachie,Whitfield,GWS,senior,6,18/07/1994,187,81,VIC,Dandenong Stingrays,129.0,"59""",GWS,LACHIE WHITFIELD_GWS
814,43139,294685,Zac,Williams,GWS,senior,29,20/09/1994,185,84,NSW,Narrandera,97.0,"23""",GWS,ZAC WILLIAMS_GWS

In [67]:
merged = pd.merge(df_sc_players, df_fanfooty_players, how='left', left_on='SC Feed ID', right_on='afl_player_id')
merged.loc[merged['fanfooty_player_id'].isna()]

,SC ID,SC Feed ID,SC Player Name,first_name_x,last_name,Fanfooty Player ID,Fanfooty Player Name,Footywire Name,AFL ID,AFL Name,Team,Position,Date of Birth,Jumper Number,player_team_id_x,fanfooty_player_id,afl_player_id,first_name_y,surname,team,status,number,birth_date,height,weight,state_of_origin,recruited_from,games,goals,short_team,player_team_id_y
57,58,290326,Matt Eagles,Matt,Eagles,NaN,NaN,NaN,NaN,NaN,BRL,DEF,NaN,NaN,MATT EAGLES_BRL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,240,1002372,Hugh Dixon,Hugh,Dixon,NaN,NaN,NaN,NaN,NaN,FRE,FWD,NaN,NaN,HUGH DIXON_FRE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
541,542,291550,Josh Walker,Josh,Walker,NaN,NaN,NaN,NaN,NaN,NTH,DEF,NaN,NaN,JOSH WALKER_NTH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN