In [1]:
import pandas as pd

In [2]:
# Load draft data and player data

draft_data = pd.read_csv('2024_draft_leagues_1283_recap_combined.csv')
draft_data

,id,league_id,user_team_id,round,pick,player_id,position,autopicked,time
0,1705893,1283,714,1,1,695,MID,0,8/03/2024 13:18
1,1705894,1283,719,1,2,138,DEF,0,8/03/2024 13:18
2,1705901,1283,718,1,3,706,RUC,0,8/03/2024 13:18
3,1705907,1283,717,1,4,459,MID,0,8/03/2024 13:18
4,1705908,1283,713,1,5,443,RUC,0,8/03/2024 13:19
...,...,...,...,...,...,...,...,...,...
179,1706317,1283,717,23,180,503,MID,0,8/03/2024 13:44
180,1706330,1283,713,23,181,263,DEF,0,8/03/2024 13:44
181,1706337,1283,716,23,182,386,MID,0,8/03/2024 13:44
182,1706340,1283,715,23,183,721,FWD,0,8/03/2024 13:45
183,1736462,1283,720,23,184,167,FWD,0,9/03/2024 13:08

In [3]:
# # Load the JSON data from the file
# with open('../../inputs/player_stats_current/player_stats_current_season_695.json', 'r') as file:
#     data = json.load(file)

# # Extract the relevant fields into a list of dictionaries
# player_match_stats = data['player_match_stats']
# extracted_data = []
# for match in player_match_stats:
#     round_number = match['round']
#     extracted_data.append({
#         'feed_id': data['feed_id'],
#         'player_id': match['player_id'],
#         'first_name': data['first_name'],
#         'last_name': data['last_name'],
#         'team_abbrev': data['team']['abbrev'],
#         'pos_1': data['positions'][0]['position'],
#         'pos_2': data['positions'][1]['position'] if len(data['positions']) > 1 else None,
#         'round': match['round'],
#         'points': match['points'],
#         'played': data['player_stats'][round_number]['total_games'],
#         'avg': data['player_stats'][round_number]['avg'],
#         'avg3': data['player_stats'][round_number]['avg3'],
#         'avg5': data['player_stats'][round_number]['avg5'],
#         'price': data['player_stats'][round_number]['price']
#     })

# # Create a DataFrame from the extracted data
# df = pd.DataFrame(extracted_data)

# # Display the DataFrame
# display(df)

In [4]:
# Get each player's data

player_data = pd.read_json('../../inputs/player_stats_pack/completestatspack_1.json')
player_data

                                          playerStats  playerMatchStats
0   {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
1   {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
2   {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
3   {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
4   {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
..                                                ...               ...
65  {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
66  {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
67  {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
68  {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
69  {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN

[70 rows x 2 columns]

In [5]:
player_data = pd.read_csv('2024_SC_Player_list.csv', index_col=0)
# player_data[player_data['last_name'] == "Bontempelli"]
player_data

,id,first_name,last_name,team_id,previous_games,previous_average,previous_total,feed_id,hs_url,injury_suspension_status,...,locked,played_status,active,team,player_stats,odds,positions,notes,position,long_team
0,1,Sam,Berry,1,4,50.75,203,1012807,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,ADE,"[{'player_id': 1, 'round': 0, 'points': 0, 'pr...",[],"[{'position': 'MID', 'position_long': 'Midfiel...",[],MID,Adelaide
1,2,Hugh,Bond,1,0,0.00,0,1023534,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,ADE,"[{'player_id': 2, 'round': 0, 'points': 0, 'pr...",[],"[{'position': 'DEF', 'position_long': 'Defende...",[],DEF,Adelaide
2,3,James,Borlase,1,4,58.25,233,1009029,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,ADE,"[{'player_id': 3, 'round': 0, 'points': 0, 'pr...",[],"[{'position': 'DEF', 'position_long': 'Defende...",[],DEF,Adelaide
3,4,Chris,Burgess,1,1,33.00,33,1000068,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,ADE,"[{'player_id': 4, 'round': 0, 'points': 0, 'pr...",[],"[{'position': 'FWD', 'position_long': 'Forward...",[],FWD,Adelaide
4,5,Jordon,Butts,1,17,41.94,713,1004995,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,ADE,"[{'player_id': 5, 'round': 0, 'points': 0, 'pr...",[],"[{'position': 'DEF', 'position_long': 'Defende...",[],DEF,Adelaide
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,775,Jake,Waterman,16,11,64.64,711,996554,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,WCE,"[{'player_id': 775, 'round': 0, 'points': 0, '...",[],"[{'position': 'FWD', 'position_long': 'Forward...",[],FWD,West Coast
775,776,Bailey J.,Williams,16,23,76.91,1769,1006114,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,WCE,"[{'player_id': 776, 'round': 0, 'points': 0, '...",[],"[{'position': 'RUC', 'position_long': 'Ruck', ...",[],RUC,West Coast
776,777,Jack,Williams,16,10,37.80,378,1020371,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,WCE,"[{'player_id': 777, 'round': 0, 'points': 0, '...",[],"[{'position': 'FWD', 'position_long': 'Forward...",[],FWD,West Coast
777,778,Alex,Witherden,16,22,84.50,1859,998128,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,WCE,"[{'player_id': 778, 'round': 0, 'points': 0, '...",[],"[{'position': 'DEF', 'position_long': 'Defende...",[],DEF,West Coast
778,779,Elliot,Yeo,16,10,80.00,800,292128,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,WCE,"[{'player_id': 779, 'round': 0, 'points': 0, '...",[],"[{'position': 'DEF', 'position_long': 'Defende...",[],DEF MID,West Coast

In [6]:
# Calculate median scores grouped by player ID

median_data = (player_data.groupby('id')['points']
               .median()
               .reset_index()
               .rename(columns={'points': 'median_score'}))
median_data

KeyError: 'Column not found: points'

In [ ]:
# Fill NA values with 0
median_data['median_score'] = median_data['median_score'].fillna(0)

# -- Combine Data
# Merge draft data with median scores

In [ ]:
heat_map_data = pd.merge(draft_data, median_data, on='player_id', how='left')

In [ ]:
# -- Prepare Positional Data
positions = ['DEF', 'MID', 'RUC', 'FWD']
pos_count = [8*5, 8*7, 8*1, 8*5]

for i, pos in enumerate(positions):
    # Filter and sort by median score for the given position
    pos_data = heat_map_data[(heat_map_data['pos_1'] == pos) | (heat_map_data['pos_2'] == pos)]
    pos_data = pos_data.sort_values(by='median_score', ascending=False).head(pos_count[i])

    # Calculate mean and standard deviation
    mean_score = pos_data['median_score'].mean()
    stdev_score = pos_data['median_score'].std()

    # Normalize scores
    pos_data[f'{pos}_norm_score'] = ((pos_data['median_score'] - mean_score) / stdev_score).round(3)

    # Add normalized scores to the main dataframe
    heat_map_data = pd.merge(heat_map_data, pos_data[['player_id', f'{pos}_norm_score']], on='player_id', how='left')

In [ ]:
# -- Calculate Final Score
heat_map_data['final_score'] = heat_map_data[['DEF_norm_score', 'MID_norm_score', 'RUC_norm_score', 'FWD_norm_score']].max(axis=1)
heat_map_data['final_score'] = heat_map_data['final_score'].round(4)

In [ ]:
# -- Save Results
# Save the final dataset to a CSV
heat_map_data.to_csv('/mnt/data/2024_draft_heat_map.csv', index=False)