In [2]:
import pandas as pd

In [3]:
# Load draft data and player data

draft_data = pd.read_csv('2024_draft_leagues_1283_recap_combined.csv')
draft_data

,id,league_id,user_team_id,round,pick,player_id,position,autopicked,time
0,1705893,1283,714,1,1,695,MID,0,8/03/2024 13:18
1,1705894,1283,719,1,2,138,DEF,0,8/03/2024 13:18
2,1705901,1283,718,1,3,706,RUC,0,8/03/2024 13:18
3,1705907,1283,717,1,4,459,MID,0,8/03/2024 13:18
4,1705908,1283,713,1,5,443,RUC,0,8/03/2024 13:19
...,...,...,...,...,...,...,...,...,...
179,1706317,1283,717,23,180,503,MID,0,8/03/2024 13:44
180,1706330,1283,713,23,181,263,DEF,0,8/03/2024 13:44
181,1706337,1283,716,23,182,386,MID,0,8/03/2024 13:44
182,1706340,1283,715,23,183,721,FWD,0,8/03/2024 13:45
183,1736462,1283,720,23,184,167,FWD,0,9/03/2024 13:08

In [126]:
# Load the JSON data from the file
with open('../../inputs/player_stats_current/player_stats_current_season_695.json', 'r') as file:
    data = json.load(file)

# Extract the relevant fields into a list of dictionaries
player_match_stats = data['player_match_stats']
extracted_data = []
for match in player_match_stats:
    round_number = match['round']
    extracted_data.append({
        'feed_id': data['feed_id'],
        'player_id': match['player_id'],
        'first_name': data['first_name'],
        'last_name': data['last_name'],
        'team_abbrev': data['team']['abbrev'],
        'pos_1': data['positions'][0]['position'],
        'pos_2': data['positions'][1]['position'] if len(data['positions']) > 1 else None,
        'round': match['round'],
        'points': match['points'],
        'played': data['player_stats'][round_number]['total_games'],
        'avg': data['player_stats'][round_number]['avg'],
        'avg3': data['player_stats'][round_number]['avg3'],
        'avg5': data['player_stats'][round_number]['avg5'],
        'price': data['player_stats'][round_number]['price']
    })

# Create a DataFrame from the extracted data
df = pd.DataFrame(extracted_data)

# Display the DataFrame
print(df)

   feed_id  player_id first_name    last_name team_abbrev pos_1 pos_2  round  \
0   297373        695     Marcus  Bontempelli         WBD   MID  None      1
1   297373        695     Marcus  Bontempelli         WBD   MID  None      2
2   297373        695     Marcus  Bontempelli         WBD   MID  None      3
3   297373        695     Marcus  Bontempelli         WBD   MID  None      4
4   297373        695     Marcus  Bontempelli         WBD   MID  None      5
5   297373        695     Marcus  Bontempelli         WBD   MID  None      6
6   297373        695     Marcus  Bontempelli         WBD   MID  None      7
7   297373        695     Marcus  Bontempelli         WBD   MID  None      8
8   297373        695     Marcus  Bontempelli         WBD   MID  None      9
9   297373        695     Marcus  Bontempelli         WBD   MID  None     10
10  297373        695     Marcus  Bontempelli         WBD   MID  None     11
11  297373        695     Marcus  Bontempelli         WBD   MID  None     12
12  297373        695     Marcus  Bontempelli         WBD   MID  None     13
13  297373        695     Marcus  Bontempelli         WBD   MID  None     14
14  297373        695     Marcus  Bontempelli         WBD   MID  None     16
15  297373        695     Marcus  Bontempelli         WBD   MID  None     17
16  297373        695     Marcus  Bontempelli         WBD   MID  None     18
17  297373        695     Marcus  Bontempelli         WBD   MID  None     19
18  297373        695     Marcus  Bontempelli         WBD   MID  None     20
19  297373        695     Marcus  Bontempelli         WBD   MID  None     21
20  297373        695     Marcus  Bontempelli         WBD   MID  None     22
21  297373        695     Marcus  Bontempelli         WBD   MID  None     23
22  297373        695     Marcus  Bontempelli         WBD   MID  None     24

    points  played      avg     avg3    avg5   price
0      126       1  126.000  126.000  126.00  724600
1      136       2  131.000  131.000  131.00  724600
2      110       3  124.000  124.000  124.00  704900
3      141       4  128.250  129.000  128.25  697700
4       73       5  117.200  108.000  117.20  664500
5      125       6  118.500  113.000  117.00  646000
6      102       7  116.143  100.000  110.20  614000
7      142       8  119.375  123.000  116.60  623100
8      135       9  121.111  126.333  115.40  634300
9       93      10  118.300  123.333  119.40  635800
10     135      11  119.818  121.000  121.40  632700
11     186      12  125.333  138.000  138.20  654900
12      99      13  123.308  140.000  129.60  671200
13     162      14  126.071  149.000  135.00  696600
14     157      15  128.133  139.333  147.80  705300
15     106      16  126.750  141.667  142.00  714000
16     108      17  125.647  123.667  126.40  695000
17     122      18  125.444  112.000  131.00  663200
18     109      19  124.579  113.000  120.40  640500
19     182      20  127.450  137.667  125.40  657700
20     119      21  127.048  136.667  128.00  670200
21     123      22  126.864  141.333  131.00  685300
22     116      23  126.391  119.333  129.80  665800

In [108]:
import pandas as pd
import json

# Load the JSON data from the file
with open('../../inputs/player_stats_current/player_stats_current_season_695.json', 'r') as file:
    data = json.load(file)

# Extract the relevant fields into a list of dictionaries
# player_match_stats = data['player_match_stats']
player_match_stats = data
# display(data)
extracted_data = []
for match in player_match_stats['player_match_stats']:
    # display(match)
    extracted_data.append({
        'feed_id': data['feed_id'],
        'player_id': match['player_id'],
        'first_name': data['first_name'],
        'last_name': data['last_name'],
        'team_abbrev': data['team']['abbrev'],
        'pos_1': data['positions'][0]['position'],
        'pos_2': data['positions'][0]['position'],
        # 'pos_1': match['position_ranks']['pos_rank_pos'],
        # 'pos_1_rank': data['pos_1'],
        # 'pos_1_round_rank': data['pos_1'],
        # 'pos_2': match['pos_2'],
        # 'pos_2_rank': match['pos_2'],
        # 'pos_2_round_rank': match['pos_2'],
        'round': match['round'],
        # 'projected_points': match['projected_points'],
        'points': match['points'],
        # 'played': match['played'],
        # 'avg': match['avg'],
        # 'avg3': match['avg3'],
        # 'avg5': match['avg5'],
        # 'price': match['price']
    })

#### IF I WANT TO GET MORE STATS, I NEED TO GET THEM FROM data['player_stats']
    
# Create a DataFrame from the extracted data
df = pd.DataFrame(extracted_data)

# Display the DataFrame
df

TypeError: list indices must be integers or slices, not str

In [44]:
# Load the JSON data
with open('../../inputs/player_stats_current/player_stats_current_season_695.json') as f:
    player_json = json.load(f)


    # data = {
    #     'player_id': game['player_id'],
    #     'round': game['round'],
    #     'points': game['points'],
    #     'team_id': game['team_id'],
    #     'opponent_id': game['opponent_id'],
    # }
data = {
    'feed_id': player_json['feed_id']
    'player_id': player_json['player_id'],
    # 'first_name': [player_json['first_name'] for player in sc_players['playerMatchStats']],
    # 'last_name': [player_json['last_name'] for player in sc_players['playerMatchStats']],
    # 'team_abbrev': [player_json['team']['abbrev'] for player in sc_players['playerMatchStats']],
    # 'pos_1': [player_json['positions'][0]['position'] for player in sc_players['playerMatchStats']],
    # 'pos_2': [player_json['positions'][1]['position'] if len(player_json['positions']) > 1 else None for player in sc_players['playerMatchStats']],
    # 'round': [int(player_json['player_stats'][0]['round']) for player in sc_players['playerMatchStats']],
    # 'projected_points': [float(player_json['player_stats'][0]['ppts']) if player_json['player_stats'][0]['ppts'] is not None else None for player in sc_players['playerMatchStats']],
    # 'points': [float(player_json['player_match_stats'][0]['points']) if player_json['player_match_stats'] else None for player in sc_players['playerMatchStats']],
    # 'played': [int(player_json['player_stats'][0]['total_games']) if player_json['player_stats'][0]['total_games'] is not None else None for player in sc_players['playerMatchStats']],
    # 'avg': [float(player_json['player_stats'][0]['avg']) if player_json['player_stats'][0]['avg'] is not None else None for player in sc_players['playerMatchStats']],
    # 'avg3': [float(player_json['player_stats'][0]['avg3']) if player_json['player_stats'][0]['avg3'] is not None else None for player in sc_players['playerMatchStats']],
    # 'avg5': [float(player_json['player_stats'][0]['avg5']) if player_json['player_stats'][0]['avg5'] is not None else None for player in sc_players['playerMatchStats']],
    # 'price': [float(player_json['player_stats'][0]['price']) if player_json['player_stats'][0]['price'] is not None else None for player in sc_players['playerMatchStats']]
}
print(data)
# # Extract the data
# data = {
#     'feed_id': [player['feed_id'] for player in sc_players],
#     # 'player_id': [int(player['id']) for player in sc_players],
#     # 'first_name': [player['first_name'] for player in sc_players],
#     # 'last_name': [player['last_name'] for player in sc_players],
#     # 'team_abbrev': [player['team']['abbrev'] for player in sc_players],
#     # 'pos_1': [player['positions'][0]['position'] for player in sc_players],
#     # 'pos_2': [player['positions'][1]['position'] if len(player['positions']) > 1 else None for player in sc_players],
#     # 'round': [int(player['player_stats'][0]['round']) for player in sc_players],
#     # 'projected_points': [float(player['player_stats'][0]['ppts']) if player['player_stats'][0]['ppts'] is not None else None for player in sc_players],
#     # 'points': [float(player['player_match_stats'][0]['points']) if player['player_match_stats'] else None for player in sc_players],
#     # 'played': [int(player['player_stats'][0]['total_games']) if player['player_stats'][0]['total_games'] is not None else None for player in sc_players],
#     # 'avg': [float(player['player_stats'][0]['avg']) if player['player_stats'][0]['avg'] is not None else None for player in sc_players],
#     # 'avg3': [float(player['player_stats'][0]['avg3']) if player['player_stats'][0]['avg3'] is not None else None for player in sc_players],
#     # 'avg5': [float(player['player_stats'][0]['avg5']) if player['player_stats'][0]['avg5'] is not None else None for player in sc_players],
#     # 'price': [float(player['player_stats'][0]['price']) if player['player_stats'][0]['price'] is not None else None for player in sc_players]
# }

# # Create a DataFrame
# player_data = pd.DataFrame(data)

# print(player_data)

297373

In [6]:
# Get each player's data

player_data = pd.read_json('../../inputs/player_stats_pack/completestatspack_1.json')
player_data

                                          playerStats  playerMatchStats
0   {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
1   {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
2   {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
3   {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
4   {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
..                                                ...               ...
65  {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
66  {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
67  {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
68  {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN
69  {'player_id': 1, 'team_id': 1, 'opponent_id': ...               NaN

[70 rows x 2 columns]

In [16]:
player_data = pd.read_csv('2024_SC_Player_list.csv', index_col=0)
# player_data[player_data['last_name'] == "Bontempelli"]
player_data

,id,first_name,last_name,team_id,previous_games,previous_average,previous_total,feed_id,hs_url,injury_suspension_status,...,locked,played_status,active,team,player_stats,odds,positions,notes,position,long_team
0,1,Sam,Berry,1,4,50.75,203,1012807,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,ADE,"[{'player_id': 1, 'round': 0, 'points': 0, 'pr...",[],"[{'position': 'MID', 'position_long': 'Midfiel...",[],MID,Adelaide
1,2,Hugh,Bond,1,0,0.00,0,1023534,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,ADE,"[{'player_id': 2, 'round': 0, 'points': 0, 'pr...",[],"[{'position': 'DEF', 'position_long': 'Defende...",[],DEF,Adelaide
2,3,James,Borlase,1,4,58.25,233,1009029,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,ADE,"[{'player_id': 3, 'round': 0, 'points': 0, 'pr...",[],"[{'position': 'DEF', 'position_long': 'Defende...",[],DEF,Adelaide
3,4,Chris,Burgess,1,1,33.00,33,1000068,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,ADE,"[{'player_id': 4, 'round': 0, 'points': 0, 'pr...",[],"[{'position': 'FWD', 'position_long': 'Forward...",[],FWD,Adelaide
4,5,Jordon,Butts,1,17,41.94,713,1004995,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,ADE,"[{'player_id': 5, 'round': 0, 'points': 0, 'pr...",[],"[{'position': 'DEF', 'position_long': 'Defende...",[],DEF,Adelaide
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,775,Jake,Waterman,16,11,64.64,711,996554,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,WCE,"[{'player_id': 775, 'round': 0, 'points': 0, '...",[],"[{'position': 'FWD', 'position_long': 'Forward...",[],FWD,West Coast
775,776,Bailey J.,Williams,16,23,76.91,1769,1006114,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,WCE,"[{'player_id': 776, 'round': 0, 'points': 0, '...",[],"[{'position': 'RUC', 'position_long': 'Ruck', ...",[],RUC,West Coast
776,777,Jack,Williams,16,10,37.80,378,1020371,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,WCE,"[{'player_id': 777, 'round': 0, 'points': 0, '...",[],"[{'position': 'FWD', 'position_long': 'Forward...",[],FWD,West Coast
777,778,Alex,Witherden,16,22,84.50,1859,998128,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,WCE,"[{'player_id': 778, 'round': 0, 'points': 0, '...",[],"[{'position': 'DEF', 'position_long': 'Defende...",[],DEF,West Coast
778,779,Elliot,Yeo,16,10,80.00,800,292128,NaN,NaN,...,False,"{'status': 'pre', 'display': 'Yet to play'}",True,WCE,"[{'player_id': 779, 'round': 0, 'points': 0, '...",[],"[{'position': 'DEF', 'position_long': 'Defende...",[],DEF MID,West Coast

In [20]:
# Calculate median scores grouped by player ID

median_data = (player_data.groupby('id')['points']
               .median()
               .reset_index()
               .rename(columns={'points': 'median_score'}))
median_data

      id  previous_average
0      1             50.75
1      2              0.00
2      3             58.25
3      4             33.00
4      5             41.94
..   ...               ...
774  775             64.64
775  776             76.91
776  777             37.80
777  778             84.50
778  779             80.00

[779 rows x 2 columns]

In [ ]:
# Fill NA values with 0
median_data['median_score'] = median_data['median_score'].fillna(0)

# -- Combine Data
# Merge draft data with median scores

In [ ]:
heat_map_data = pd.merge(draft_data, median_data, on='player_id', how='left')

In [ ]:
# -- Prepare Positional Data
positions = ['DEF', 'MID', 'RUC', 'FWD']
pos_count = [8*5, 8*7, 8*1, 8*5]

for i, pos in enumerate(positions):
    # Filter and sort by median score for the given position
    pos_data = heat_map_data[(heat_map_data['pos_1'] == pos) | (heat_map_data['pos_2'] == pos)]
    pos_data = pos_data.sort_values(by='median_score', ascending=False).head(pos_count[i])

    # Calculate mean and standard deviation
    mean_score = pos_data['median_score'].mean()
    stdev_score = pos_data['median_score'].std()

    # Normalize scores
    pos_data[f'{pos}_norm_score'] = ((pos_data['median_score'] - mean_score) / stdev_score).round(3)

    # Add normalized scores to the main dataframe
    heat_map_data = pd.merge(heat_map_data, pos_data[['player_id', f'{pos}_norm_score']], on='player_id', how='left')

In [ ]:
# -- Calculate Final Score
heat_map_data['final_score'] = heat_map_data[['DEF_norm_score', 'MID_norm_score', 'RUC_norm_score', 'FWD_norm_score']].max(axis=1)
heat_map_data['final_score'] = heat_map_data['final_score'].round(4)

In [ ]:
# -- Save Results
# Save the final dataset to a CSV
heat_map_data.to_csv('/mnt/data/2024_draft_heat_map.csv', index=False)